name: Build and Release APK

on:
  workflow_dispatch:
    inputs:
      tag: 
        description: 'Tag to build'
        required: false
        default: 'latest'

jobs:
  build_apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9' # Specify your Flutter version
          channel: 'stable'
          cache: true

      - name: Get version name from tag
        id: get_version
        run: |
          echo "::set-output name=version::${{ github.event.inputs.tag }}"

      - name: Build APK
        run: |
          flutter build apk --release --build-name=${{ steps.get_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: wormgpt_agent_apk
          path: build/app/outputs/flutter-apk/app-release.apk
